# Generated by Django 3.0.4 on 2020-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200419_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/Sanoto.san/PycharmProjects/balabolka/media/avatars/'),
        ),
    ]
